# EminentAi startup: backend (ASP.NET Core) + web UI (Vite)
$ErrorActionPreference = "Stop"

# -- Free ports 5210 and 5173 -------------------------------------------------
function Clear-Port($port) {
    Write-Host "   Checking port $port..."
    $connections = Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue
    if ($connections) {
        $ownerPids = $connections.OwningProcess | Select-Object -Unique
        foreach ($ownerPid in $ownerPids) {
            Write-Host "   Freeing port $port (pid $ownerPid)..."
            Stop-Process -Id $ownerPid -Force -ErrorAction SilentlyContinue
        }
        Start-Sleep -Milliseconds 400
    }
}

Clear-Port 5210
Clear-Port 5173

# -- Detect LAN cert (generated by setup-network.ps1) ------------------------
$certsReady = (Test-Path "$PSScriptRoot\certs\eka.eminent.ai.pem") -and `
              (Test-Path "$PSScriptRoot\certs\eka.eminent.ai-key.pem")
$launchUrl  = if ($certsReady) { "https://eka.eminent.ai" } else { "http://localhost:5173" }

# -- Ollama check -------------------------------------------------------------
try {
    $null = Invoke-WebRequest -Uri "http://127.0.0.1:11434/api/tags" -Method Get -UseBasicParsing -TimeoutSec 2
} catch {
    Write-Warning "Ollama is not responding on 127.0.0.1:11434."
}

# -- Start backend ------------------------------------------------------------
Write-Host "Starting EminentAi backend on http://0.0.0.0:5210 (network-accessible) ..." -ForegroundColor Cyan
$backendJob = Start-Job -ScriptBlock {
    param($root)
    Set-Location $root
    $dotnet = if (Get-Command "dotnet" -ErrorAction SilentlyContinue) { "dotnet" } else { "C:\Program Files\dotnet\dotnet.exe" }
    & $dotnet run --project src/EminentAi.Api
} -ArgumentList $PSScriptRoot

# -- Start web UI -------------------------------------------------------------
Write-Host "Starting web UI (network-accessible) ..." -ForegroundColor Cyan
$frontendJob = Start-Job -ScriptBlock {
    param($root)
    Set-Location "$root\web"
    npm run dev -- --host
} -ArgumentList $PSScriptRoot

Start-Sleep -Seconds 4

Write-Host ""
Write-Host "  Local:   http://localhost:5173" -ForegroundColor Yellow
Write-Host "  Network: http://192.168.1.189:5173  (other laptops on the same Wi-Fi)" -ForegroundColor Green
if ($certsReady) {
    Write-Host "  HTTPS:   https://eka.eminent.ai  (port 443 -> 5173 proxy)" -ForegroundColor Cyan
}
Write-Host ""

Write-Host "Opening $launchUrl ..." -ForegroundColor Yellow
Start-Process $launchUrl

Write-Host "EminentAi is running. Press Ctrl+C to stop." -ForegroundColor Green

# Keep script alive; pipe job output to console
try {
    while ($true) {
        Receive-Job -Job $backendJob  -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "[backend]  $_" }
        Receive-Job -Job $frontendJob -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "[frontend] $_" }
        Start-Sleep -Seconds 1
    }
} finally {
    Write-Host "Stopping jobs..."
    Stop-Job   $backendJob,  $frontendJob -ErrorAction SilentlyContinue
    Remove-Job $backendJob,  $frontendJob -ErrorAction SilentlyContinue
}
