import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Load LAN certs if present (generated by setup-network.ps1 on Windows).
// Absent on Mac/CI → Vite falls back to plain HTTP, no config change needed.
let httpsOptions: { cert: Buffer; key: Buffer } | undefined
try {
  httpsOptions = {
    cert: fs.readFileSync(path.resolve(__dirname, '../certs/eka.eminent.ai.pem')),
    key:  fs.readFileSync(path.resolve(__dirname, '../certs/eka.eminent.ai-key.pem')),
  }
} catch {
  // certs absent — HTTP mode
}

export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0',
    https: httpsOptions,
    proxy: {
<<<<<<< Updated upstream
      // Forward all /api/* calls to the ASP.NET backend so the browser
      // never hits CORS issues and works on any port Vite picks.
=======
>>>>>>> Stashed changes
      '/api': {
        target: 'http://127.0.0.1:5210',
        changeOrigin: true,
      },
<<<<<<< Updated upstream
      // Mailpit dashboard API
=======
      // Proxy Mailpit API to avoid CORS — browser calls /mailpit-api/...
      // Vite rewrites it to http://localhost:8025/...
>>>>>>> Stashed changes
      '/mailpit-api': {
        target: 'http://localhost:8025',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/mailpit-api/, ''),
      },
    },
  },
})
